# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
