# Generated by Django 2.2.10 on 2020-06-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200612_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isAdvanced',
            new_name='isArt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isBeginner',
            new_name='isBookReview',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isExpLearning',
            new_name='isFilmReview',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isIntermediate',
            new_name='isTravel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isStory',
        ),
    ]
