# Generated by Django 2.2.10 on 2020-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isArt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isBookReview',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isFilmReview',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isInterview',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isTravel',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('interviews', 'Interviews'), ('arts', 'Arts & Culture'), ('films', 'Film Reviews'), ('books', 'Book Reviews'), ('travel', 'Travel & Experience')], default='interviews', max_length=20),
        ),
    ]
